name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3 # 最新バージョンに更新
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest # 最新バージョンに更新
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name takaaaaaan
          git config user.email taka20030902@gmail.com
          git add -A .
          git commit -m "Update 3D contribution graph"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
